export const appScreens = {
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  VERIFICATION_SCREEN: 'VERIFICATION_SCREEN',
  AUTH_NAVIGATOR: 'Auth_NAVIGATOR',
  INTRODUCE_NAVIGATOR: 'INTRODUCE_NAVIGATOR',
  MAIN_NAVIGATOR: 'MAIN_NAVIGATOR',
  TAB_NAVIGATOR: 'TAB_NAVIGATOR',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
};
