export const appScreens = {
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  VERIFICATION_SCREEN: 'VERIFICATION_SCREEN',
};
